### ISSUE TITLE
Incomplete scripts

### ISSUE THREAD

**Issue by PsychoBitchy** [Primechain/yobichain#1]
Hi.
I tried your scripts against a freshly installed Ubuntu instance ( Ubuntu 14.04.5 LTS x64 ).
1- You totally omitted apache2, curl && PHP7.0 install in your scripts which caused your script to fail.
```
sudo apt-get install php7.0 libapache2-mod-php7.0 php7.0-mysql php7.0-curl php7.0-json
sudo apt-get install apache2
Sudo apt-get install curl
```
Then I wasn't able to pass the py libcrypto install, which failed with 
`warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.`

Lastly, as i was sudoing, the home `.cache` didn't have the correct permissions.
I'm going to try again with a screen.log and will add more detail.

[EDIT] **Install worked flawlessly on ubuntu 14.10 with preinstall of Curl, php7.0 & apache2.**
Thank you a lot!

**Comment by shinamarora** [comment]
Great that its working.
