### ISSUE TITLE
Suggestion on email and question about email

### ISSUE THREAD

**Issue by verronlunatic** [Primechain/yobichain#18]
Is this service "register user using "somethingblue-api" service? or can it be using postfix?

**Comment by primechain-dev** [comment]
Yobichain currently doesn't use send-in-blue API service for email. But you need to configure the sendgrid API key in EMAIL_PROVIDER_API_KEY parameter in `yobichain-web/primechain_functions/config.php` for email functionalities to work.
**Postfix is not supported.**

**Comment by verronlunatic** [comment]
ok thanks for the info.
looking forward postfix for the future intergrated. i mean can send via simple postfix or postfix relay
by the way great job bro!~

**Comment by primechain-dev** [comment]
Support for other mailing platforms is currently not in the roadmap. But we'll surely consider it for future releases. Thank you.
