### ISSUE TITLE
Issue installing yobichain multichain

### ISSUE THREAD

**Issue by jeffward01** [Primechain/yobichain#8]
Hello!

I really would like to try out your software and learn from it!  Upon installing I got this error:

![image](https://user-images.githubusercontent.com/12589359/30414120-defe85a8-98d6-11e7-8774-0f7ec2c1fd73.png)

The error occurs during yobichain installation, while Multichain is configuring:

----------------------------------------
INSTALLING & CONFIGURING MULTICHAIN.....
----------------------------------------
2017-09-14 05:56:08 URL:https://www.multichain.com/download/multichain-latest.tar.gz [10055511/10055511] -> "multichain-latest.tar.gz.1" [1]
multichain-1.0.1/
multichain-1.0.1/multichain-util
multichain-1.0.1/multichain-cli
multichain-1.0.1/README.txt
multichain-1.0.1/multichaind
multichain-1.0.1/multichaind-cold
cp: cannot stat 'multichain-1.0-*/multichain*': No such file or directory

-------------------------------------------

Is this a bug? I have installed php, and all other software.  Maybe the versions changed?

**Comment by jeffward01** [comment]
I manually installed multichain, and now have this error during installation:

![image](https://user-images.githubusercontent.com/12589359/30414729-d40537ac-98d9-11e7-8956-470f86fc4760.png)

----------------------------------------
CREATING AND CONFIGURING STREAMS.....
----------------------------------------
{"method":"createrawsendfrom","params":["1SD9V2DxYj6iRL4tUQJvVQ4jg5crSvz5FBQweL",{},[{"create":"stream","name":"proof_of_existence","open":false,"details":{"purpose":"Stores hashes of files"}}],"send"],"id":1,"chain_name":"epicChain"}

error code: -8
error message:
Upgrades are not supported by this protocol version

**Comment by geekongit** [comment]
The issue was with the archive's extract directory name for the latest version of multichain. It has been fixed. Please re-install. It should work now.
